# DOCKERFILE

# CHANGE TO BE YOUR IMAGE
# GCC FOR C FILES, ETC
FROM baseImage 

ARG SERVERFILE
ARG WKG_DIR
ARG PORT

# Expose port if necessary 

# Compile your files with the args above, add more if necessary

# Run your server with the args above